keys:
  - &me >-
    2572AB455CFE0D0AD221434E841AD164D942D3D9,
    890B1B924CBD066D0485C682FC8C6BD101A0EF00

  #> nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
  - &hypnos age1l5h004t4fvcexnwa7uc2mvmpr3g5q2fry5ld86vvg993tgcyqd5qu5qhqk

stores:
  yaml:
    indent: 2

creation_rules:
  - path_regex: secrets.yaml
    age: *hypnos
    pgp: *me
